### ISSUE TITLE
[macOS Ventura, Xcode 14.2, M1 Pro] Get an error when install SwagGen

### ISSUE THREAD

**Issue by rigamikhail27** [yonaskolb/SwagGen#313]
Hi @yonaskolb!
Thank you for this lib!
I tried to install it and got an error for all types like below. Do you have any ideas?)

**brew**
```
brew install SwagGen
==> Fetching yonaskolb/swaggen/SwagGen
==> Downloading https://github.com/yonaskolb/SwagGen/archive/4.7.0.tar.gz
Already downloaded: /Users/a27/Library/Caches/Homebrew/downloads/f36d827f276ed453e352be8214b3efac05cbee29f9659c070075bafe4221bebe--SwagGen-4.7.0.tar.gz
==> Installing SwagGen from yonaskolb/swaggen
==> make install PREFIX=/opt/homebrew/Cellar/SwagGen/4.7.0
Last 15 lines from /Users/a27/Library/Logs/Homebrew/SwagGen/01.make:
2023-01-05 18:25:41 +0000

make
install
PREFIX=/opt/homebrew/Cellar/SwagGen/4.7.0

swift build --disable-sandbox -c release --arch arm64 --arch x86_64
error: xcbuild executable at '/Library/Developer/SharedFrameworks/XCBuild.framework/Versions/A/Support/xcbuild' does not exist or is not executable
make: *** [build] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!

/opt/homebrew/Library/Homebrew/utils/github/api.rb:310:in `raise_error': Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}] (GitHub::API::ValidationFailedError)
	from /opt/homebrew/Library/Homebrew/utils/github/api.rb:238:in `open_rest'
	from /opt/homebrew/Library/Homebrew/utils/github.rb:179:in `search'
	from /opt/homebrew/Library/Homebrew/utils/github.rb:40:in `search_issues'
	from /opt/homebrew/Library/Homebrew/utils/github.rb:73:in `issues_for_formula'
	from /opt/homebrew/Library/Homebrew/exceptions.rb:498:in `fetch_issues'
	from /opt/homebrew/Library/Homebrew/exceptions.rb:493:in `issues'
	from /opt/homebrew/Library/Homebrew/exceptions.rb:549:in `dump'
	from /opt/homebrew/Library/Homebrew/brew.rb:154:in `rescue in <main>'
	from /opt/homebrew/Library/Homebrew/brew.rb:142:in `<main>'
/opt/homebrew/Library/Homebrew/formula.rb:2526:in `block in system': Failed executing: make install PREFIX=/opt/homebrew/Cellar/SwagGen/4.7.0 (BuildError)
	from /opt/homebrew/Library/Homebrew/formula.rb:2462:in `open'
	from /opt/homebrew/Library/Homebrew/formula.rb:2462:in `system'
	from /opt/homebrew/Library/Taps/yonaskolb/homebrew-swaggen/Formula/SwagGen.rb:34:in `install'
	from /opt/homebrew/Library/Homebrew/build.rb:177:in `block (3 levels) in install'
	from /opt/homebrew/Library/Homebrew/utils.rb:605:in `with_env'
	from /opt/homebrew/Library/Homebrew/build.rb:139:in `block (2 levels) in install'
	from /opt/homebrew/Library/Homebrew/formula.rb:1326:in `block in brew'
	from /opt/homebrew/Library/Homebrew/formula.rb:2692:in `block (2 levels) in stage'
	from /opt/homebrew/Library/Homebrew/utils.rb:605:in `with_env'
	from /opt/homebrew/Library/Homebrew/formula.rb:2691:in `block in stage'
	from /opt/homebrew/Library/Homebrew/resource.rb:158:in `block (2 levels) in unpack'
	from /opt/homebrew/Library/Homebrew/download_strategy.rb:116:in `chdir'
	from /opt/homebrew/Library/Homebrew/download_strategy.rb:116:in `chdir'
	from /opt/homebrew/Library/Homebrew/download_strategy.rb:103:in `stage'
	from /opt/homebrew/Library/Homebrew/resource.rb:154:in `block in unpack'
	from /opt/homebrew/Library/Homebrew/mktemp.rb:77:in `block in run'
	from /opt/homebrew/Library/Homebrew/mktemp.rb:77:in `chdir'
	from /opt/homebrew/Library/Homebrew/mktemp.rb:77:in `run'
	from /opt/homebrew/Library/Homebrew/resource.rb:266:in `stage_resource'
	from /opt/homebrew/Library/Homebrew/resource.rb:153:in `unpack'
	from /opt/homebrew/Library/Homebrew/resource.rb:127:in `stage'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	from /opt/homebrew/Library/Homebrew/formula.rb:2671:in `stage'
	from /opt/homebrew/Library/Homebrew/formula.rb:1319:in `brew'
	from /opt/homebrew/Library/Homebrew/build.rb:133:in `block in install'
	from /opt/homebrew/Library/Homebrew/utils.rb:605:in `with_env'
	from /opt/homebrew/Library/Homebrew/build.rb:128:in `install'
	from /opt/homebrew/Library/Homebrew/build.rb:229:in `<main>'
```

**mint**
```
mint install yonaskolb/SwagGen                                 
🌱 Finding latest version of SwagGen
🌱 Cloning SwagGen 4.7.0
🌱 Resolving package
error: 'github.com_yonaskolb_swaggen': Invalid manifest
/private/var/folders/s1/m32136tj39bgvc264bjg_89w0000gq/T/mint/github.com_yonaskolb_SwagGen/Package.swift:2:8: error: no such module 'PackageDescription'
import PackageDescription
       ^
🌱 Encountered error during "swift package resolve". Use --verbose to see full output
🌱  Failed to resolve SwagGen 4.7.0 with SPM
```

**make**
```
make install
swift build --disable-sandbox -c release --arch arm64 --arch x86_64
error: xcbuild executable at '/Library/Developer/SharedFrameworks/XCBuild.framework/Versions/A/Support/xcbuild' does not exist or is not executable
make: *** [build] Error 1
```

**Comment by rigamikhail27** [comment]
Fixed by this: https://github.com/yonaskolb/SwagGen/issues/311
